dist: trusty
language: ruby
rvm:
  - 2.4.1
bundler_args: --without development
cache: bundler
addons:
  apt_packages:
    - pandoc
  code_climate:
    repo_token: 243e5ab59244b7a1d3fb97d56bfe9961307ad558cb4a7cbeec3c85104e9ee11b
before_install:
  - export TZ=Europe/Zurich
before_script:
  - cp config/secrets.travis.yml config/secrets.yml
script:
  - RAILS_ENV=test bundle exec rails db:setup
  - bundle exec rails spec
notifications:
  email:
    recipients:
      - joshua.muheim@access-for-all.ch
    on_failure: change
    on_success: change