dist: trusty
language: ruby
rvm:
  - 2.2.6
bundler_args: --without development
cache: bundler
addons:
  apt_packages:
    - pandoc
  code_climate:
    repo_token: <%= Rails.application.secrets['code_climate_repo_token'] %>
before_script:
  - unlink config/secrets.yml
  - cp config/secrets.travis.yml config/secrets.yml
script:
  - RAILS_ENV=test bundle exec rails db:setup
  - bundle exec rails spec
notifications:
  email:
    recipients:
      - <%= Rails.application.secrets['notifications_email_recipient'] %>
    on_failure: change
    on_success: change